export { sendEmail, type OutboundEmail } from "./mailer";
export {
  bookingConfirmation,
  bookingReminder,
  bookingFollowUp,
  bookingNoShowFollowUp,
  bookingRescheduled,
  bookingRequested,
  newBookingRequest,
  bookingDeclined,
  bookingCancellation,
  bookingRunningLate,
  bookingMessage,
  pollInvitation,
  pollVoteUpdate,
  workflowEmail,
  dailyBriefing,
  teamBriefing,
  meetingRecap,
  guardrailAlert,
  activationShareLink,
  activationConnectCalendar,
  weeklyDigest,
  firstBookingCelebration,
  applyTemplateVars,
  WORKFLOW_VARIABLES,
  type BookingEmailData,
  type PollInvitationData,
  type PollVoteUpdateData,
  type DailyBriefingData,
  type TeamBriefingData,
  type MeetingRecapData,
  type GuardrailAlertData,
  type ActivationEmailData,
  type WeeklyDigestData,
} from "./templates";
