export { sendEmail, type OutboundEmail } from "./mailer";
export {
  bookingConfirmation,
  bookingReminder,
  bookingFollowUp,
  bookingNoShowFollowUp,
  bookingRescheduled,
  bookingRequested,
  newBookingRequest,
  bookingDeclined,
  bookingCancellation,
  bookingRunningLate,
  bookingMessage,
  workflowEmail,
  dailyBriefing,
  teamBriefing,
  meetingRecap,
  guardrailAlert,
  applyTemplateVars,
  WORKFLOW_VARIABLES,
  type BookingEmailData,
  type DailyBriefingData,
  type TeamBriefingData,
  type MeetingRecapData,
  type GuardrailAlertData,
} from "./templates";
